# Generated by Django 4.0.4 on 2022-05-27 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Фото', models.ImageField(upload_to='', verbose_name='Фото')),
                ('Фото1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('Фото2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('Фото3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('Адрес', models.TextField()),
                ('Район', models.CharField(blank=True, choices=[('Центр', 'Центр'), ('Южный', 'Южный'), ('Западный', 'Западный'), ('Северный', 'Северный'), ('Восточный', 'Восточный')], max_length=20, null=True)),
                ('Дом', models.PositiveIntegerField()),
                ('Подъезд', models.PositiveIntegerField()),
                ('Этаж', models.IntegerField()),
                ('Квартира', models.PositiveIntegerField()),
                ('Комнат', models.PositiveIntegerField()),
                ('Цена', models.PositiveIntegerField()),
                ('Телефон', models.TextField(blank=True, max_length=40, null=True)),
                ('Описание', models.TextField()),
                ('Date', models.DateField(auto_now_add=True, null=True)),
                ('Updated', models.DateField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
