# Generated by Django 4.0.4 on 2022-06-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='Цена_наруки',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
